name: Gradle test report merge

on: workflow_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        test: ${{ fromJSON('["1","0","2"]') }}

    steps:
      - uses: actions/checkout@v3

      - name: cancel job
        if: matrix.test == '0'
        run: |
          echo "Canceled"
          exit 1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            test
            --no-daemon
            --continue

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ format('test-report-ubuntu-{0}', matrix.test) }}
          path: build/test-results/test/binary

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ format('test-report-windows-{0}', matrix.test) }}
          path: build/test-results/test/binary

  merge_report:
    needs: [run_tests]
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: reports

      - name: debug
        run: |
          ls -R reports

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Merge reports (ubuntu)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            mergeTestReports
            -PtestReportMergePrefix=test-report-ubuntu

      - name: Merge reports (windows)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            mergeTestReports
            -PtestReportMergePrefix=test-report-windows

      - name: Upload merged reports
        uses: actions/upload-artifact@v3
        with:
          path: test-report-*
